sudo: false
language: go
go:
  - 1.8
  - 1.8.1
  - 1.8.2
  - 1.8.3
  - 1.8.4
  - 1.8.5
  - 1.9
  - 1.9.1
  - 1.9.2
before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=gear-csrf.coverprofile
  - goveralls -coverprofile=gear-csrf.coverprofile -service=travis-ci